apiVersion: v1
kind: Service
metadata:
  name: {{ include "stolon.proxy.serviceName" . }}
  namespace: {{ include "stolon.namespace" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
    app.kubernetes.io/component: proxy
  {{- with .Values.proxy.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.proxy.service.type }}
  {{- if ne .Values.network.ipFamily "IPv4" }}
  ipFamilyPolicy: {{ include "stolon.ipFamilyPolicy" . }}
  ipFamilies:
  {{- include "stolon.ipFamilies" . | nindent 4 }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") .Values.proxy.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.proxy.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.proxy.service.type "LoadBalancer") .Values.proxy.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- toYaml .Values.proxy.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  ports:
    - name: postgresql
      port: {{ .Values.proxy.service.port }}
      targetPort: postgresql
      protocol: TCP
      {{- if and (eq .Values.proxy.service.type "NodePort") .Values.proxy.service.nodePort }}
      nodePort: {{ .Values.proxy.service.nodePort }}
      {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.port }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "stolon.proxy.selectorLabels" . | nindent 4 }}
