{{- if and .Values.postgresql.createSecrets (or .Values.postgresql.superuserPassword .Values.postgresql.replicationPassword) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.secretName" . }}
  namespace: {{ include "stolon.namespace" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.superuserPassword }}
  {{ .Values.postgresql.superuserPasswordKey }}: {{ .Values.postgresql.superuserPassword | b64enc | quote }}
  {{- end }}
  {{- if .Values.postgresql.replicationPassword }}
  {{ .Values.postgresql.replicationPasswordKey }}: {{ .Values.postgresql.replicationPassword | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.pgbackrest.enabled (or .Values.pgbackrest.s3AccessKey .Values.pgbackrest.gcsCredentials) (not .Values.pgbackrest.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "stolon.pgbackrest.secretName" . }}
  namespace: {{ include "stolon.namespace" . }}
  labels:
    {{- include "stolon.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.pgbackrest.s3AccessKey }}
  AWS_ACCESS_KEY_ID: {{ .Values.pgbackrest.s3AccessKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.pgbackrest.s3SecretKey }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.pgbackrest.s3SecretKey | b64enc | quote }}
  {{- end }}
  {{- if .Values.pgbackrest.gcsCredentials }}
  GOOGLE_APPLICATION_CREDENTIALS: {{ .Values.pgbackrest.gcsCredentials | quote }}
  {{- end }}
{{- end }}
